apiVersion: v1
kind: Service
metadata:
  name: books-service
spec:
  selector:
    app: books-service
  ports:
    - protocol: TCP
      port: 4545
      targetPort: 4545
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
        - name: books-container
          image: gerrydockeruser/books-service:latest  # Ganti dengan nama dan versi image Anda
          ports:
            - containerPort: 4545
  
